import type { BadgeCourse } from "./badgeCatalog";

export const trailAwardCategories = [
  "Ascensos y reconocimientos",
  "Premios de liderazgo",
  "Premios de destreza requeridos",
  "Premios de destreza",
  "Reconocimiento de logro",
  "Estudios bíblicos",
  "Adiestramiento juvenil",
] as const;

export type TrailAwardCategory = (typeof trailAwardCategories)[number];

export type TrailAwardCatalogItem = BadgeCourse & {
  category: TrailAwardCategory;
  detail: string;
  aliases?: string[];
};

type IndexedAwardsOptions = {
  group: string;
  prefix: string;
  names: string[];
  category: TrailAwardCategory;
  detail: string;
  ids?: string[];
  aliases?: (index: number, name: string) => string[];
};

const indexedAwards = ({
  group,
  prefix,
  names,
  category,
  detail,
  ids,
  aliases,
}: IndexedAwardsOptions): TrailAwardCatalogItem[] =>
  names.map((name, index) => ({
    id: ids?.[index] || `${group}-${prefix}-${String(index + 1).padStart(2, "0")}`,
    src: `/trail-awards/${group}/${prefix}-${String(index + 1).padStart(2, "0")}.png`,
    alt: name,
    category,
    detail,
    aliases: aliases?.(index, name),
  }));

const singleAward = (
  group: string,
  id: string,
  file: string,
  alt: string,
  category: TrailAwardCategory,
  detail: string,
  aliases?: string[]
): TrailAwardCatalogItem => ({
  id,
  src: `/trail-awards/${group}/${file}.png`,
  alt,
  category,
  detail,
  aliases,
});

const numberedBiblicalAwards = (
  group: string,
  color: string,
  count: number
) =>
  indexedAwards({
    group,
    prefix: "biblico",
    names: Array.from(
      { length: count },
      (_, index) => `Premio bíblico ${color} ${String(index + 1).padStart(2, "0")}`
    ),
    category: "Estudios bíblicos",
    detail: `Premio bíblico ${color}`,
    aliases: (index) => [
      `Premio bíblico ${String(index + 1).padStart(2, "0")}`,
      `Bíblico ${index + 1}`,
    ],
  });

const youthAwards = (group: string): TrailAwardCatalogItem[] => {
  const awards: TrailAwardCatalogItem[] = [
    {
      id: "ilj",
      src: "/trail-awards/common/introduccion-liderazgo-juvenil.png",
      alt: "Introducción al Liderazgo Juvenil",
      category: "Adiestramiento juvenil",
      detail: "Adiestramiento juvenil",
      aliases: ["ILJ"],
    },
    {
      id: "cbd",
      src: "/trail-awards/common/lider-siervo.png",
      alt: "El Líder Siervo",
      category: "Adiestramiento juvenil",
      detail: "Adiestramiento juvenil",
      aliases: ["Líder Siervo"],
    },
  ];

  return awards.map((award) => ({
    ...award,
    detail: `${award.detail} de ${group}`,
  }));
};

const navegantesLogros = [
  "Aventuras sobre ruedas",
  "Día de campo",
  "Artes",
  "Ser un amigo",
  "Juegos",
  "Ayudando a la comunidad",
  "Misiones generales",
  "Historia de la familia",
  "Defensor de la Palabra",
  "Ayudando a la iglesia",
  "Ayudar a un vecino",
  "Cocinando",
  "Cuerpo limpio",
  "Banderas",
  "Folclor",
  "Historia de la iglesia",
  "Mapa",
  "Bombero",
  "Manualidad",
  "Visitando lugares",
  "Clamor de gozo",
  "Hacedor de la Palabra",
  "Naturaleza",
  "Ayudando en el hogar",
  "El gobierno",
  "Ayudar al líder",
  "Títeres",
  "Dios está trabajando",
  "El arca de Noé",
  "Ayudando en el manejo de dinero",
  "Guardián de la ley",
  "Historia",
  "Exploradores en la comunidad",
  "Evangelización",
  "De paseo",
  "Ayudando a la patrulla",
  "La escuela",
  "En el aire",
  "Cuerpo fuerte",
  "Escuela dominical o bíblica",
  "Deportes",
  "Evento deportivo",
  "Atando nudos",
  "Seguridad",
  "¿Qué hay en la tele?",
  "Contándole a otros sobre Jesús",
  "Cuidando el mundo de Dios",
  "Trabajo en equipo",
  "Electivo del líder: comunidad",
  "Electivo del líder: hogar",
  "Electivo del líder: ministerio",
];

const pionerosDestrezas = [
  "Artes",
  "Astronomía",
  "Lenguaje de señas básico",
  "Cestería",
  "Lectura de la Biblia",
  "Estudio de las aves",
  "Ajedrez",
  "Iglesia",
  "Colecciones",
  "Brújula",
  "Cocinando",
  "Dardos",
  "Conociendo la discapacidad",
  "Cuidado del perro",
  "Vida en familia",
  "Huella digital",
  "Fogata",
  "Pesca",
  "Pasatiempo",
  "Patinaje sobre hielo",
  "Patinaje en línea",
  "Estudio de los insectos",
  "Amarres",
  "Aplicando la ley",
  "Modelos y diseños",
  "Música",
  "Líderes nacionales",
  "Pintura",
  "Mascotas",
  "Trenes",
  "Lectura",
  "Cohetes",
  "Patinaje sobre ruedas",
  "Nudos y cuerdas",
  "Remo",
  "Seguridad",
  "Escultura",
  "Ciudadanos mayores",
  "Herramientas",
  "Clima",
  "La fauna",
];

const seguidoresDestrezas = [
  "Académicos",
  "Conociendo la discapacidad avanzado",
  "Natación avanzada",
  "Radio aficionado",
  "Arquería",
  "Aviación",
  "Soltero",
  "Excursiones",
  "Béisbol",
  "Baloncesto",
  "Lectura de la Biblia",
  "Corneta",
  "Campismo",
  "Seguridad en el campamento",
  "Canoas",
  "Carpintería",
  "Misiones cristianas",
  "Servicio cristiano",
  "Historia de la iglesia",
  "Comunicaciones",
  "Computadoras",
  "Prevención del crimen",
  "Ciclismo",
  "Cocinando en ollas holandesas",
  "Preparación de las emergencias",
  "Energía",
  "Ciencias ambientales",
  "Historia de la familia",
  "Seguridad en caso de incendio",
  "Primeros auxilios y RCP",
  "Fútbol",
  "Silvicultura",
  "Jardinería",
  "Caminatas",
  "Reparación en el hogar",
  "Seguridad en el hogar",
  "Equitación",
  "Servicio internacional",
  "Manualidades en cuero",
  "Salvavidas",
  "Estudio de la naturaleza",
  "Orientación con la brújula",
  "Fotografía",
  "Pionerismo",
  "Botánica",
  "Alfarería",
  "Refugios primitivos",
  "Trampas primitivas",
  "Oratoria",
  "Titiritero",
  "Estudio de los reptiles",
  "El arte de vender",
  "Patineta",
  "Deportes",
  "Filatelia",
  "Natación",
  "Tenis",
  "Transporte de vehículos pesados",
  "Tallado en madera",
  "Lucha libre",
];

const exploradoresDestrezas = [
  "Arquería avanzada",
  "Excursionismo avanzado",
  "Control de tránsito aéreo",
  "Sistema del avión",
  "Rendimiento del avión",
  "Cría de animales",
  "Arquitectura",
  "Energía atómica",
  "Mecánica automotriz",
  "Carreras de aviación",
  "Historia de la aviación",
  "Fundamentos meteorológicos para la aviación",
  "Aerodinámica básica",
  "Lectura de la Biblia",
  "Navegando en bote",
  "Química",
  "Cinematografía",
  "Odontología",
  "Dibujantes",
  "Economía",
  "Electricidad",
  "Electrónica",
  "Ingeniería",
  "Administración de granjas o haciendas",
  "Mecánica agrícola",
  "Reglamento del aire 1 (OACI)",
  "Reglamento del aire 2 (OACI)",
  "Navegación aérea",
  "Fisiología del vuelo",
  "Plan de vuelo",
  "Preparación del vuelo",
  "Entrenamiento del piloto",
  "Pesca con mosca",
  "Idioma extranjero",
  "Geología",
  "Golf",
  "Artes gráficas",
  "Curtidos de cuero",
  "Misiones domésticas de construcción",
  "Educación para la caza sin riesgo",
  "Introducción a la aviación",
  "Periodismo",
  "Navegando en kayak",
  "Arquitectura paisajística",
  "Derecho",
  "Mamíferos",
  "Albañilería",
  "Medicina",
  "Metalurgia",
  "Botes de motor",
  "Ciclismo de montaña",
  "Vuelo sobre montañas",
  "Oceanografía",
  "Dramas y ceremonias",
  "Plomería",
  "Salud pública",
  "Rappelling",
  "Escalada en roca",
  "Aeronaves con alas rotatorias",
  "Navegando",
  "Buceo con tanque de oxígeno",
  "Lenguaje de señas",
  "Esquiando",
  "Buceo sin tanque de oxígeno",
  "Tabla sobre nieve",
  "Conservación del suelo y agua",
  "Ciencia solar",
  "Topografía",
  "Atletismo en pista",
  "Seguridad en el tráfico",
  "Medicina veterinaria",
  "Instructor de seguridad en el agua",
  "Esquí acuático",
  "Peso y balance",
  "Rafting",
  "Sobrevivencia en la selva",
  "Campamento de invierno",
  "Trabajo en madera",
  "Misiones mundiales",
  "Misiones mundiales de construcción",
  "Misiones juveniles",
];

const trailAwardsByGroup: Record<string, TrailAwardCatalogItem[]> = {
  Navegantes: [
    singleAward("navegantes", "navegantes-bronce", "ascenso-bronce", "Senda Bronce", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("navegantes", "navegantes-plata", "ascenso-plata", "Senda Plata", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("navegantes", "navegantes-oro", "ascenso-oro", "Senda Oro", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("navegantes", "navegantes-cinta-logro", "cinta-logro", "Cinta de logro de Navegantes", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    ...indexedAwards({
      group: "navegantes",
      prefix: "logro",
      names: navegantesLogros,
      category: "Reconocimiento de logro",
      detail: "Reconocimiento de logro opcional",
    }),
  ],
  Pioneros: [
    singleAward("pioneros", "pioneros-bronce", "ascenso-bronce", "Senda del Nudo Cuadrado Bronce", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("pioneros", "pioneros-plata", "ascenso-plata", "Senda del Nudo Vuelta de Escota Plata", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("pioneros", "pioneros-oro", "ascenso-oro", "Senda del Nudo As de Guía Oro", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("pioneros", "pioneros-cinta-logro", "cinta-logro", "Cinta de logro de Pioneros", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    singleAward("pioneros", "pioneros-estrella-bronce", "estrella-bronce", "Estrella de Bronce", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    ...indexedAwards({
      group: "pioneros",
      prefix: "liderazgo",
      names: ["Liderazgo 101", "Liderazgo 102", "Liderazgo 103", "Liderazgo 104", "Liderazgo 105", "Liderazgo 106"],
      category: "Premios de liderazgo",
      detail: "Premio de liderazgo rojo",
      ids: ["101", "102", "103", "104", "105", "106"],
    }),
    ...indexedAwards({
      group: "pioneros",
      prefix: "requerido",
      names: ["Biblia", "Primeros auxilios", "Misiones mundiales"],
      category: "Premios de destreza requeridos",
      detail: "Premio de destreza azul requerido",
    }),
    ...indexedAwards({
      group: "pioneros",
      prefix: "destreza",
      names: pionerosDestrezas,
      category: "Premios de destreza",
      detail: "Premio de destreza azul",
    }),
    ...numberedBiblicalAwards("pioneros", "naranja", 15),
    ...youthAwards("Pioneros"),
  ],
  Seguidores: [
    singleAward("seguidores", "seguidores-bronce", "ascenso-bronce", "Senda del Nudo Ballestrinque Bronce", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("seguidores", "seguidores-plata", "ascenso-plata", "Senda del Nudo Vuelta de Braza Plata", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("seguidores", "seguidores-oro", "ascenso-oro", "Senda del Nudo Vuelta de Pescador Oro", "Ascensos y reconocimientos", "Ascenso anual"),
    singleAward("seguidores", "seguidores-cinta-logro", "cinta-logro", "Cinta de logro de Seguidores de la Senda", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    singleAward("seguidores", "seguidores-estrella-plata", "estrella-plata", "Estrella de Plata", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    ...indexedAwards({
      group: "seguidores",
      prefix: "liderazgo",
      names: ["Liderazgo 201", "Liderazgo 202", "Liderazgo 203", "Liderazgo 204", "Liderazgo 205", "Liderazgo 206"],
      category: "Premios de liderazgo",
      detail: "Premio de liderazgo amarillo",
      ids: ["201", "202", "203", "204", "205", "206"],
    }),
    ...indexedAwards({
      group: "seguidores",
      prefix: "requerido",
      names: ["Biblia", "Misiones mundiales", "Preparación física"],
      category: "Premios de destreza requeridos",
      detail: "Premio de destreza verde requerido",
    }),
    ...indexedAwards({
      group: "seguidores",
      prefix: "destreza",
      names: seguidoresDestrezas,
      category: "Premios de destreza",
      detail: "Premio de destreza verde",
      aliases: (_, name) =>
        name === "Computadoras"
          ? ["Uso de la computadora", "Uso de computadora"]
          : name === "Oratoria"
            ? ["Public speaking"]
            : [],
    }),
    ...numberedBiblicalAwards("seguidores", "café", 15),
    ...youthAwards("Seguidores"),
  ],
  Exploradores: [
    singleAward("exploradores", "exploradores-cinta-logro", "cinta-logro", "Cinta de logro de Exploradores", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    singleAward("exploradores", "exploradores-estrella-oro", "estrella-oro", "Estrella de Oro", "Ascensos y reconocimientos", "Reconocimiento de grupo"),
    ...indexedAwards({
      group: "exploradores",
      prefix: "etapa",
      names: ["Senda E1", "Senda E2", "Senda E3"],
      category: "Ascensos y reconocimientos",
      detail: "Ascenso de Exploradores",
      ids: ["e1", "e2", "e3"],
    }),
    ...indexedAwards({
      group: "exploradores",
      prefix: "liderazgo",
      names: ["Liderazgo 301", "Liderazgo 302", "Liderazgo 303", "Liderazgo 304", "Liderazgo 305", "Liderazgo 306"],
      category: "Premios de liderazgo",
      detail: "Premio de liderazgo celeste",
      ids: ["301", "302", "303", "304", "305", "306"],
    }),
    ...indexedAwards({
      group: "exploradores",
      prefix: "requerido",
      names: ["Presupuesto y finanzas", "Ciudadanía", "Verdades fundamentales"],
      category: "Premios de destreza requeridos",
      detail: "Premio de destreza platino requerido",
    }),
    ...indexedAwards({
      group: "exploradores",
      prefix: "destreza",
      names: exploradoresDestrezas,
      category: "Premios de destreza",
      detail: "Premio de destreza platino",
    }),
    ...indexedAwards({
      group: "exploradores",
      prefix: "biblico",
      names: ["Reto espiritual azul", "Reto espiritual rojo", "Reto espiritual verde", "Reto espiritual bronce", "Reto espiritual plata", "Reto espiritual oro"],
      category: "Estudios bíblicos",
      detail: "Premio bíblico de reto espiritual",
    }),
    ...youthAwards("Exploradores"),
    singleAward("exploradores", "senda-sable", "senda-sable", "Senda del Sable", "Adiestramiento juvenil", "Adiestramiento juvenil"),
    singleAward("exploradores", "medalla-logro-honor", "medalla-logro-honor", "Medalla de Oro al Logro de Honor", "Ascensos y reconocimientos", "Premio por alcanzar el nivel más alto en los cuatro grupos"),
  ],
};

export const getTrailAwardCatalog = (group: string) =>
  trailAwardsByGroup[group] || [];

export const trailAwardCounts = Object.fromEntries(
  Object.entries(trailAwardsByGroup).map(([group, awards]) => [group, awards.length])
) as Record<string, number>;
